export type ApiSpec = {
  category: string;
  event: (ApiSpecRestApiEvent | ApiSpecSqsEvent | ApiSpecWebsocketEvent)[];
  operationId: string;
  /**
   * @description name of the serverless function
   * @default ApiSpec#operationId
   */
  name?: string;
  /**
   * @autogenerated
   * @description relative path of the api handler
   */
  uri?: string;
  /**
   * @deprecated
   */
  desc: string;
  description: string;
  parameters: {
    [key: string]: {
      /**
       * @deprecated
       */
      req: boolean;
      required: boolean;
      type: "string" | "number" | "boolean" | "array" | "object";
      description: string;
      in: "query" | "header" | "cookie";
    };
  };
  requestBody: Record<string, unknown>;
  responses: {
    [key: string]: {
      description: string;
      content: string;
      schema: {
        type: "object" | "array";
        properties: {};
      };
    };
  };
};

type ApiSpecSqsEvent = {
  type: "sqs";
  sqs: string;
  batchSize?: number;
};
type ApiSpecWebsocketEvent = {
  type: "websocket";
  method: "websocket";
  route: "$disconnect" | "$connect" | string;
};
type ApiSpecRestApiEvent = {
  type: "REST";
  method: HttpMethod;
  authorizer?: string;
};

type HttpMethod =
  | "GET"
  | "POST"
  | "DELETE"
  | "PUT"
  | "Get"
  | "Post"
  | "Delete"
  | "Put"
  | "get"
  | "post"
  | "delete"
  | "put";
